/* The name and version of this software distribution. These
 * originates from AM_INIT_AUTOMAKE in the configure.in file. */
#define PACKAGE "configure-generated"
#define VERSION "configure-generated"

/* Define to enable sanity checking on memory allocation and casting */
#undef DEBUG_ALLOC

/* Define if zlib should be used */
#undef WITH_ZLIB

/* Define if zlib.h is present */
#undef HAVE_ZLIB_H

/* Define to enable pty support */
#undef WITH_PTY_SUPPORT

/* Define to enable fallback to SSH1 */
#undef WITH_SSH1_FALLBACK

/* Location of the SSH1 daemon */
#undef SSHD1

/* Define if IDEA should be used */
#undef WITH_IDEA

/* Define to enable tcp forwarding */
#undef WITH_TCP_FORWARD

/* Define to indicate that shutdown seems to work properly */
#undef SHUTDOWN_WORKS_WITH_UNIX_SOCKETS

/* Define if the compiler understands __attribute__ */
#undef HAVE_ATTRIBUTE

/* Define if a we have working UNIX98 pty handling */
#undef HAVE_UNIX98_PTYS

/* openpty() available? */
#undef HAVE_OPENPTY

/* For BSD-style pty allocation */
#undef PTY_BSD_SCHEME_FIRST_CHARS
#undef PTY_BSD_SCHEME_SECOND_CHARS

#undef PTY_BSD_SCHEME

/* syslog() available? */
#undef HAVE_SYSLOG

/* struct utmp has a ut_host member */
#undef HAVE_UT_HOST

/* struct utmp has a ut_addr member */
#undef HAVE_UT_ADDR

/* struct utmp has a ut_addr_v6 member */
#undef HAVE_UT_ADDR_V6

/* Define to support non-standard dsa signatures generated by ssh2 */
#undef DATAFELLOWS_SSH2_SSH_DSA_KLUDGE
