#! /bin/sh

# Fake ssh-server for use by the ssh1-fallback-test

inet_mode=no
version=''

echo 1>&2 fake-sshd1: starting
echo 1>&2 nargs = $#, args = "$@"

while [ $# -ne 0 ] ; do
    case "$1" in
	-i)
	    inet_mode=yes
	    ;;
	-V)
	    shift
	    version=$1
	    ;;
	*)
	    echo 1>&2 fake-sshd1: Invalid argument "$1"
	    exit 1
	    ;;
    esac
    shift
done

echo 1>&2 fake-sshd1: Received version "$version"
echo 1>&2 fake-sshd1: inet_mode = "$inet_mode"

if [ "$inet_mode" != yes ] ; then exit 1; fi

case "$version" in
    SSH-1.*)
	echo SSH-1.99-fake-sshd1
	echo a-packet
	;;
    *)
	exit 1
	;;
esac
