#! /bin/sh

echo Test lsh --stop-gateway

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

spawn_lshd && spawn_lsh --start-gateway \
  && exec_lshg echo foo | grep foo >/dev/null \
  && ../lsh --stop-gateway -p $PORT $LOCALHOST \
  && sleep 2 \
  && ( if exec_lshg echo foo; then false ; else true ; fi ) \
  && [ ! -f "$LSH_PIDFILE" ] && test_success

test_done
