#! /bin/sh

echo lsh, ipv6 test

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

need_ipv6

INTERFACE="[::1]"
LOCALHOST="::1"

spawn_lshd && run_lsh "exit 0" && test_success

test_done
