#! /bin/sh

# Tests the key generation programs

echo Testing lsh-keygen DSA key generation 

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

rm -f foo foo.pub
../lsh-keygen -a dsa | ../lsh-writekey -o foo \
  && ../sexp-conv < foo && [ -s foo -a -s foo.pub ] && test_success
