#! /bin/sh

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

echo lsh, test login, login-auth-mode

rm -f test.out1

LSHD_FLAGS="$LSHD_FLAGS --login-auth-mode --login-shell=/bin/cat --no-password --no-publickey"

spawn_lshd && exec_lsh <../lshd > test.out1
cat ../lshd > test.out2

compare_output "lsh-login-test"
