#! /bin/sh

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

echo lsh, cat test

rm -f test.out1

spawn_lshd && exec_lsh "cat `pwd`/../lshd" > test.out1
cat ../lshd > test.out2

compare_output "lsh-cat-test"
