#! /bin/sh

# Tests connecting with lsh. In order to use this, you must already
# have lsh set up so that you can login without password.

# This restriction can be fixed if we add an option to lshd to use a
# custom passwd-file.

echo lsh, test 6, using various encryption algorithms

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

OLD_FLAGS="$LSH_FLAGS"

ALGORITHMS="arcfour twofish blowfish 3des aes rijndael cast128 all"

test_success

LSHD_FLAGS="$LSHD_FLAGS -c all"

spawn_lshd && for c in $ALGORITHMS ; do 
    echo Trying encryption flag $c
    if LSH_FLAGS="$OLD_FLAGS -c $c" exec_lsh "exit"; then
	echo "   Ok"
    else
	echo "   Fail"; test_fail
    fi
done
