#! /bin/sh

echo lsh, test 10

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

# Traditional BSD pty:s are currentlynot supported.
[ -c /dev/ptmx ] || test_skip

LSH_FLAGS="$LSH_FLAGS -t"

spawn_lshd && run_lsh "tty" && test_success

test_done
