#! /bin/sh

# Checks that connection fails if we don't have an known_hosts file
echo lsh, test 7

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

spawn_lshd && ! ../lsh -nt --host-db=/dev/null $LSH_FLAGS -p $PORT localhost true \
	   && test_success
