#! /bin/sh

echo Testing lshd --use-example-config

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

LSHD_CONFIG_DIR=/dev/null

spawn_lshd --use-example-config && run_lsh "exit 0" && test_success

test_done
