#! /bin/sh

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

echo lshg, cat test

rm -f test.out1

spawn_lshd && spawn_lsh --start-gateway \
    && exec_lshg "cat `pwd`/../lshd" > test.out1
cat ../lshd > test.out2

compare_output "lshg-cat-test"
