#! /bin/sh

echo lshg test 1

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

need_lshg

spawn_lshd && spawn_lsh -G && \
  echo foo | exec_lshg cat | grep foo > /dev/null && test_success

test_done
