#! /bin/sh

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

need_lshg

echo lshg, cat test

rm -f test.out1

spawn_lshd && spawn_lsh -G && exec_lshg "cat `pwd`/../lshd" > test.out1
cat ../lshd > test.out2

compare_output "lsh-cat-test"
