#! /bin/sh

if [ -z "$srcdir" ] ; then
  srcdir="`pwd`"
fi

. $srcdir/functions.sh

# Create home directory for tests
rm -rf "$TEST_HOME"
mkdir "$TEST_HOME"

HOME="$TEST_HOME"
export HOME

echo "Creating seed file"
../lsh-make-seed -q --sloppy

echo "Creating identity.pub for tests"
../lsh-keygen -a dsa -l2 -c none

echo "Authorizing key for login"
"$srcdir/../lsh-authorize" "$HOME/.lsh/identity.pub"

echo "Creating test password"
../lsh-keygen -a symmetric --bit-length 32 -o "$TEST_HOME/test-passwd"

(echo "#/bin/sh"
 echo cat '"'$TEST_HOME/test-passwd'"') > "$TEST_HOME/write-passwd"
 
echo "Creating utmp/wtmp logs"
cat /dev/null > $LSHD_UTMP
cat /dev/null > $LSHD_WTMP

test_success
