#! /bin/sh

# Tests the key generation programs

echo Testing lsh-writekey with no argument

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

rm -rf temphome && mkdir temphome
HOME="`pwd`/temphome" ../lsh-writekey < $srcdir/key-1.private \
  && [ -s "$HOME/.lsh/identity" -a -s "$HOME/.lsh/identity.pub" ] && test_success
