#! /bin/sh

echo lshg X11, test 5

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

need_xvfb

set -x

# Passing variables to an invocation of a shell function seems
# somewhat flaky, so we use separate commands for setting all
# variables. The sub-process prevents LSHG_FLAGS to leak to the next
# command.
spawn_xvfb \
  && spawn_lshd \
  && spawn_lsh --start-gateway \
  && (DISPLAY=$TEST_DISPLAY;
      export DISPLAY;
      LSHG_FLAGS="$LSHG_FLAGS --x11";
       exec_lshg $XMODMAP > /dev/null ) \
  && if exec_lshg $XMODMAP > /dev/null ; then false ; else test_success; fi

test_done


