#! /bin/sh

echo lsh X11, test 2

if [ -z "$srcdir" ] ; then
  srcdir=`pwd`
fi

. $srcdir/functions.sh

need_xvfb

# Passing variables to an invocation of a shell function seems
# somewhat flaky, so we use separate commands for setting all
# variables. The sub-process prevents LSHG_FLAGS to leak to the next
# command.
spawn_xvfb \
  && spawn_lshd \
  && (DISPLAY=$TEST_DISPLAY;
      export DISPLAY;
      LSH_FLAGS="$LSH_FLAGS --x11";
      exec_lsh "$XMODMAP" > /dev/null) \
  && if exec_lsh "$XMODMAP" > /dev/null; then false ; else true; fi \
  && test_success

test_done
